language: java
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxf android-sdk_r18-linux.tgz
  # setup your ANDROID_HOME and PATH environment variables
  - export ANDROID_HOME=~/builds/flerda/Anki-Android/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # Only update the SDK for the tools and platform-tools and whatever API level
  # you are building for android.
  - android update sdk --filter 1,2 --no-ui --force
  - android list sdk
  - android update sdk --filter 3 --no-ui --force
  - android update project --path ~/builds/flerda/Anki-Android
script: "ant clean debug"
